config/routes.rb
Ticketee::Application.routes.draw do


  #devise_for :users

  devise_for :users, :controllers => {
    :registrations => "registrations",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  root :to => "projects#index"
  resources :users
  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
      member do 
      post :watch
      end
    end
  end
  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end
  ### API
  namespace :api do
    namespace :v1 do
      resources :projects, defaults: {format: :json} do
        resources :tickets, defaults: {format: :json}
      end
    end
    namespace :v2 do
      resources :projects, defaults: {format: :json} do
        resources :tickets, defaults: {format: :json}
      end
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true
  has_many :tickets, dependent: :delete_all
  belongs_to :user
 #def searcher 
    #label :tag, :from => :tags, :field => :name
 #end
  def last_ticket
    tickets.last
  end
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::V1::BaseController

  before_filter :find_project, :only => [:show, :update]

  def index
    respond_with(Project.all.where('user_id = ?', current_user.id))
  end
  def create
    project = Project.new(params[:project])
    if project.save
      respond_with(project, :location => api_v1_project_path(project))
    else
      respond_with(project)
    end
  end
  def show
    respond_with(@project, :methods => "last_ticket")
  end

  def update
    @project.update_attributes(params[:project])
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private
  def find_project
    @project = Project.all.where('user_id = ?', current_user) 
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking for could not be found."
    redirect_to projects_path
  end
end

app/controllers/api/v2/projects_controller.rb
class Api::V2::ProjectsController < Api::V2::BaseController

  before_filter :find_project, :only => [:show, :update]

  def index
    respond_with(Project.all.where('user_id = ?', current_user.id))
  end
  def create
    project = Project.new(params[:project])
    if project.save
      respond_with(project, :location => api_v1_project_path(project))
    else
      respond_with(project)
    end
  end
  def show
    respond_with(@project, :methods => "last_ticket")
  end

  def update
    @project.update_attributes(params[:project])
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private
  def find_project
    @project = Project.all.where('user_id = ?', current_user) 
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking for could not be found."
    redirect_to projects_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_filter :authenticate_user!

  caches_action :show, :cache_path => (proc do 
    project_path(project_path(params[:id]) +"/#{current_user.id}/#{params[:page] || 1}")
  end)

  #before_action :authorize_admin!, except: [:index, :show]
  before_action :set_project, only: [:show,
                                     :edit,
                                     :update,
                                     :destroy]
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save
      flash[:notice] = "Project has been created."
      redirect_to @project
    else
      flash[:alert] = "Project has not been created."
      render :action => "new"
    end
  end

  def show
    @tickets = @project.tickets
    @tickets = @tickets.page(params[:page]).per(5)
  end

  def edit
  end


  def update
    if @project.update(project_params)
      flash[:notice] = "Project has been updated."
      redirect_to @project
    else
      flash[:alert] = "Project has not been updated."
      render action: "edit"
    end
  end

  def destroy
    @project.destroy
    flash[:notice] = "Project has been destroyed."
    redirect_to projects_path
  end

  private
  def project_params
    params.require(:project).permit(:name, :description)
  end

  private
  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking" +
      " for could not be found."
    redirect_to projects_path
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %><br />
    <%= f.submit %>
  <% end %>

app/views/projects/edit.html.erb
<h2>Edit project</h2>
<%= render "form" %>

app/views/projects/index.html.erb
<h2>Projects</h2>
<%= link_to "New Project", new_project_path %>
<ul>
  <% @projects.each do |project| %>
    <br/>
    <li><%= link_to project.name, project %></li>
<% end %>
</ul>

app/views/projects/new.html.erb
<h2>New Project</h2>
<%= render "form" %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<h2><%= @project.name %></h2>
<%= link_to "Edit Project", [:edit, @project]%>
<%= link_to "Delete Project", [@project], method: :delete%>
<%= link_to "New Ticket", new_project_ticket_path(@project) %>
<%= form_tag search_project_tickets_path(@project), :method => :get do %>
  <%= label_tag "search" %>
  <%= text_field_tag "search", params[:search] %>
  <%= submit_tag "Search" %>
<% end %>

<%= paginate @tickets %>
<ul id='tickets'>
    <% @tickets.each do |ticket| %>
    <li>
      <%= render ticket.state if ticket.state %>
      #<%= ticket.id %> - <%= link_to ticket.title, [@project, ticket] %>
  </li>
<% end %>
</ul>