config/routes.rb
Ticketee::Application.routes.draw do


  #devise_for :users

  devise_for :users, :controllers => {
    :registrations => "registrations",
    :omniauth_callbacks => "users/omniauth_callbacks"
  }

  root :to => "projects#index"
  resources :users
  resources :projects do
    resources :tickets do
      collection do
        get :search
      end
      member do 
      post :watch
      end
    end
  end
  resources :tickets do
    resources :comments
    resources :tags do
      member do
        delete :remove
      end
    end
  end
  ### API
  namespace :api do
    namespace :v1 do
      resources :projects, defaults: {format: :json} do
        resources :tickets, defaults: {format: :json}
      end
    end
    namespace :v2 do
      resources :projects, defaults: {format: :json} do
        resources :tickets, defaults: {format: :json}
      end
    end
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

 before_filter :authenticate_user! , except: [:show, :index]

  def remove
    @ticket = Ticket.find(params[:ticket_id])
    @tag = Tag.find(params[:id])
    @ticket.tags -= [@tag] 
    @ticket.save
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= f.label :tag_names, "Tags" %>
<%= f.text_field :tag_names %>

app/views/tags/_tag.html.erb
<span class='tag'>
  
<%= link_to "x",remove_ticket_tag_path(@ticket, tag), 
:method => :delete,
:remote => true,
:id => "delete-#{tag.name.parameterize}" %> 
<%= tag.name %>
</span>

app/views/tags/remove.js.erb
$('#delete-<%= @tag.name.parameterize %>').parent().remove();